apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    spec.ingressClassName: nginx
spec:
  ingressClassName: "nginx"
  rules:
    - host: my-micro-posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-srv
                port:
                  number: 4000
